# Generated by Django 2.2.5 on 2020-07-12 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='profile_pics')),
                ('Full_name', models.CharField(max_length=256)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1, null=True)),
                ('Phone_Number', models.CharField(max_length=12)),
                ('Email', models.EmailField(max_length=264, unique=True)),
                ('Country', models.CharField(max_length=264)),
                ('State', models.CharField(max_length=264)),
                ('City', models.CharField(max_length=264)),
                ('Address', models.TextField()),
                ('Membership', models.CharField(choices=[('2RLM', '2100 Rs Lifetime Membership'), ('2RLPM', '21000 Rs Lifetime Patron Membership'), ('1LRST', '1Lakh Rs S.A.F Trustee'), ('1LRSPT', '11Lakh Rs S.A.F Patron Trustee'), ('5LRSBT', '51Lakh Rs S.A.F Board of Trustee')], max_length=6, null=True)),
                ('Career_choose', models.CharField(choices=[('BI', 'Business & Industry'), ('JL', 'Judicial & Legal Services'), ('BP', 'Bureaucrats & Public Servant'), ('DP', 'Defence, Police & Paramilitary Forces'), ('NC', 'NCC Cadets'), ('VJ', 'VIPR Jan(Pujari/Brahmins)'), ('PR', 'Public Representatives'), ('NF', 'Nandanaar Families'), ('SO', 'Social Organisations'), ('DO', 'Doctors'), ('YO', 'Youths'), ('OT', 'Others')], max_length=264, null=True)),
            ],
        ),
    ]
