# Generated by Django 2.2.5 on 2020-07-13 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_auto_20200712_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='What_best_describe_you',
            new_name='Career',
        ),
        migrations.AlterField(
            model_name='myuser',
            name='Phone_Number',
            field=models.CharField(max_length=12, unique=True),
        ),
    ]
