# Generated by Django 2.2.5 on 2020-07-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20200713_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='Membership',
            field=models.CharField(choices=[('2100', '2100 Rs Lifetime Membership'), ('21000', '21000 Rs Lifetime Patron Membership'), ('100000', '1Lakh Rs S.A.F Trustee'), ('1100000', '11Lakh Rs S.A.F Patron Trustee'), ('5100000', '51Lakh Rs S.A.F Board of Trustee')], max_length=6, null=True),
        ),
    ]
